### ISSUE TITLE
Filter by "NotChecked" tag.

### ISSUE THREAD

**Issue by isupovs** [adrianiftode/HealthChecks.Extensions#1]
Hello, is there an option not to display health checks with "NotChecked" tag. I tried to use `Predicate` of `HealthCheckOptions`. It works weird. It can be hide if the tag will appear in tags array but it won't be displayed when the tags array becomes empty.

**Comment by adrianiftode** [comment]
Hi, I haven't followed this, I was wondering if you just filter on the client side.

**Comment by isupovs** [comment]
I just decided to recreate webhost and add or not healthchecks on startup.
